### ISSUE TITLE
Scrolling not always smooth

### ISSUE THREAD

**Issue by bviefhues** [lavalleeale/Lemmios#12]
Not sure if I should report that, but here we go...

I noticed that scrolling through posts is not always 100% smooth. Sometimes the list is stuck a bit. Not much but noticeable.

Experiencing this on an iPhone 11 Pro, on iOS 16.5.1.

**Comment by Genfood** [comment]
Same for me, if I scroll through the feed it stutters a lot.

**Comment by lavalleeale** [comment]
Should be a lot better in the latest update, sorry this took me so long to get to
