### ISSUE TITLE
Image too large

### ISSUE THREAD

**Issue by bviefhues** [lavalleeale/Lemmios#13]
I get an "Image too large" error when attenoting to post an image. This is for photos from the device camera (iPhone 11 Pro)

Depending on the image store provider, the app should offer to shrink the image through compression or resizing.

**Comment by lavalleeale** [comment]
Yeah, the issue is that pictrs (Lemmy default) does not report the max image size back so we would have to manually guess and check (or ask user) and those both seem like subpar solutions

**Comment by bviefhues** [comment]
Hmm, what is the way to post images then? 🤔

**Comment by bviefhues** [comment]
@lavalleeale I still get the error on version 1.2.36.
