### ISSUE TITLE
Freeze on post

### ISSUE THREAD

**Issue by bviefhues** [lavalleeale/Lemmios#15]
For me, the app freezes when showing this post: https://lemmy.world/post/1312946 and scrolling down. The app is responsive until scrolling to the bottom of the post. Then it freezes and requires a force-quit. 

The comments are not displayed. The app freezes right before that. 

This is the only post i fond so far with this issue. Will look out for more.

**Comment by bviefhues** [comment]
Additionaly, after creating the issue, force-quitting abd re-opening the app, the feed overview does not show the subscribed communities any more. They are still on the account, as verified with another app, but not shown in lemmyios. 

Subscribed communities come back after switching account and then switching account back.

**Comment by lavalleeale** [comment]
Yes, the new account switcher had a regression in reloading the currently logged in account which is fixed by 1.2.32, do you still have the error with the post?

**Comment by bviefhues** [comment]
Works now. Thanks for fixing.
