### ISSUE TITLE
Please add a way to re-blur nsfw pictures

### ISSUE THREAD

**Issue by ManikandanUV** [lavalleeale/Lemmios#2]
Once unblurred, there is no way to reblur them. Either only show them unblurred when opened, or add way to reblur them again

**Comment by lavalleeale** [comment]
This sounds like a good feature, but how would you imagine the UX? I dislike always reblurring on close, and I cant think of an easy and intuitive place to put a button, do you think a setting would suffice?

**Comment by ManikandanUV** [comment]
> This sounds like a good feature, but how would you imagine the UX? I dislike always reblurring on close, and I cant think of an easy and intuitive place to put a button, do you think a setting would suffice?

If you don't want to reblur, Mlem has an eye button in a corner of the image that you can look into. 

![image](https://github.com/lavalleeale/Lemmios/assets/13487652/57af3b6d-4982-4689-bec8-1e6b0f4ec4c1)
