### ISSUE TITLE
User name tap area too large

### ISSUE THREAD

**Issue by bviefhues** [lavalleeale/Lemmios#20]
The user name tap area on posts in the post list is too large. One accidentaly ends on the user page when wanting to show the post. 

Suggest to limit the tap target area to the actual user name.

**Comment by lavalleeale** [comment]
Just to verify, which direction do you think it is too large in?

**Comment by bviefhues** [comment]
I am refering to the area below the user name, that one includes the comment count. It seems quite natural to tap there for opening the post. 

Additionally, it is most comfortable to tap at the bottom of a post, since that requires least thumb movement.

**Comment by lavalleeale** [comment]
Hey, I was never able to encounter this issue by myself, but there have been many UI changes and I am wondering if you are still encountering it?
