### ISSUE TITLE
Image upload needs improvement

### ISSUE THREAD

**Issue by bviefhues** [lavalleeale/Lemmios#30]
I know i kind of reported this in #13 already and appreciate the update, but feel this still does not resolve the issue. 

1) The option to resize is offered as error message, with a visibility timeout. Its really difficult to even read the error message. 

2) The Resize dialog is cryptic. It does not say what unit the resize value is. No idea what a sensible value is. The 5.000 default applies so much compression that the result is not useable. 

3) The app should resize automatically to the max size supported by the instance being posted to. Not sure if possible to query that value from instances but that would be the best user experience, i think.

**Comment by lavalleeale** [comment]
Yeah, I wish I could query it from the instance but I asked the developers of Lemym and they confirmed it is not something that's available, the Lemmy website has the same error with no option to resize, I think for now the best I can do is add units and a more sensible default.

**Comment by lavalleeale** [comment]
Closing this with the hopes of opening it again in the future once the API can provide this data

**Comment by bviefhues** [comment]
I have peeked how Voyager (former wefwef) does it: compresd to 990k file size. 

https://github.com/aeharding/voyager/blob/main/src/services/lemmy.ts
