### ISSUE TITLE
Swipe to go back gesture lags and stutters

### ISSUE THREAD

**Issue by Genfood** [lavalleeale/Lemmios#44]
On nearly all pages swiping to go back, stutters and is laggy.

I made a video to show this, but I don't know if this behaviour is visible on the video:

https://github.com/lavalleeale/Lemmios/assets/11618226/96fbd47b-ee13-4047-879d-4cbfa3dd90ba

**Comment by lavalleeale** [comment]
Should be fixed

**Comment by Genfood** [comment]
Imo it isn't much better. 😅
