### ISSUE TITLE
Issue on creating a new post

### ISSUE THREAD

**Issue by Genfood** [lavalleeale/Lemmios#57]
I have just created a new post a noticed two bugs.  
First the user displayed is wrong (it displays jackolantern not genfood):  
https://github.com/lavalleeale/Lemmios/assets/11618226/da7a4dd2-d839-4bba-9b70-e43306122ee0

Second the post itself is cropped and does not show the whole content:  
![image](https://github.com/lavalleeale/Lemmios/assets/11618226/498fd267-d1d4-4847-a886-dfc24044a9cc)

The last one seems to be not related to creating a new post, and is probably intended. So ignore this one 😁

**Comment by lavalleeale** [comment]
Huh, I've never seen that before, is Jackolatern an account you have signed in? Does this happen every time you post?

**Comment by Genfood** [comment]
No, not my account but the previous post is made from this account maybe that is related.

**Comment by Genfood** [comment]
Just tested it and yes it happened again. As you can see it is the author of the precious post.

https://github.com/lavalleeale/Lemmios/assets/11618226/458ae161-257e-4638-9ac3-e4a384b91dff
