### ISSUE TITLE
User name is not displayed in local feed

### ISSUE THREAD

**Issue by Genfood** [lavalleeale/Lemmios#59]
The username of the authors post won't be displayed in the _local_ feed, but it is working in _all_ and _home_.

![image](https://github.com/lavalleeale/Lemmios/assets/11618226/798ae2b3-49f9-417d-8cb7-408a6d3b36f9)

**Comment by lavalleeale** [comment]
I'm not quite getting it, all special (what I'm calling non community specific) feeds should show the community the post is from and not the authors name? Could you show me a side by side of whats different?

**Comment by Genfood** [comment]
I would assume to see the authors name anywhere, maybe expect of scrolling through a users page.

Why shouldn't the author names be displayed in my local feed, but will be displayed in local?

For example in this community the author name is shown on one post but not on an other one.

![image](https://github.com/lavalleeale/Lemmios/assets/11618226/77348ec7-9089-4bd3-8cca-ee2aab97d4f0)

I would expect to see the author name on every post.

**Comment by lavalleeale** [comment]
It is added in a setting
