### ISSUE TITLE
Multi communities

### ISSUE THREAD

**Issue by bviefhues** [lavalleeale/Lemmios#6]
Support multi communities (or community groups). Offer a user interface for configuring a number of communities under a common name/label. That name would be app/device local only.

In the Traverse tab, show multi communities in an iwn section and treat them like any community, i.e. offer to view, but with posts from all included communities.

This feature would be great to aggregate similar communities across instances.

For additional insight: Apollo had this feature.

**Comment by lavalleeale** [comment]
Yeah, I would love to add this feature but lemmy does not have support (reddit did) for it so it would mean making a separate request for each community and then combining them locally into a single feed which would have mixed results (at best) with different sorts

**Comment by bviefhues** [comment]
https://github.com/LemmyNet/lemmy/issues/818

**Comment by lavalleeale** [comment]
Closing until https://github.com/LemmyNet/lemmy/issues/818 is resolved
