### ISSUE TITLE
Accounts on multiple instances

### ISSUE THREAD

**Issue by bviefhues** [lavalleeale/Lemmios#8]
It seems that the current Multi Account functionality is bound to a single instance, the one used for the first account login. 

Enhancement: for additional accounts allow logins to other/separate instances.

**Comment by lavalleeale** [comment]
Just to verify, does switching instances (in settings) and then adding multiple accounts solve your problem? Definitely needs better UI though I agree.

**Comment by bviefhues** [comment]
Ok, I have now realized that changing the instance in Settings indeed changes the account. 

The UI should allow this in one place. A login should consist of instance, user name and password. The account selection screen should offer a list of username@instance. 

Plus, all the instances I am on are not included in the apps default instance list, so I need to type them every time I change.
